// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-e4EmzXcozGu015S4w1HYD1QDLtbbPnU',
    appId: '1:1095450589828:web:cc9d4f10f8c28db2f760d1',
    messagingSenderId: '1095450589828',
    projectId: 'brondo-d4f88',
    authDomain: 'brondo-d4f88.firebaseapp.com',
    storageBucket: 'brondo-d4f88.appspot.com',
    measurementId: 'G-WRS3XP25EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY71cNENXJZAv2VvG2NJef1w-VD5pEixU',
    appId: '1:1095450589828:android:fd125262763d98d1f760d1',
    messagingSenderId: '1095450589828',
    projectId: 'brondo-d4f88',
    storageBucket: 'brondo-d4f88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3t7nC9Y6QnltOmsQeesMMVrbZV-rzuM',
    appId: '1:1095450589828:ios:c8b583f47d7fc9b3f760d1',
    messagingSenderId: '1095450589828',
    projectId: 'brondo-d4f88',
    storageBucket: 'brondo-d4f88.appspot.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3t7nC9Y6QnltOmsQeesMMVrbZV-rzuM',
    appId: '1:1095450589828:ios:8e583a2fa96ddb68f760d1',
    messagingSenderId: '1095450589828',
    projectId: 'brondo-d4f88',
    storageBucket: 'brondo-d4f88.appspot.com',
    iosBundleId: 'com.example.brondo.RunnerTests',
  );
}
